EXP_NAME: FlashSD15

# Dataset
SHARDS_PATH_OR_URLS:
  - pipe:cat /root/flash-diffusion/pokemon_shards/shards-00000.tar
VALIDATION_PROMPTS:
  - A beautiful red car on the beach at sunset, 4k, photorealistic, awesome.
  - A whale with a big mouth and a rainbow on its back.
  - A cute cat with a bow tie and a monocle.
  - A raccoon reading a book in a lush forest.


# Model
LORA: True
LORA_RANK: 32
K: [32, 32, 32, 32]
NUM_ITERATIONS_PER_K: [5000, 5000, 5000, 5000]
GUIDANCE_MIN: 3.0
GUIDANCE_MAX: 13.0
DISTILL_LOSS_TYPE: lpips
UCG_KEYS: [text]
TIMESTEP_DISTRIBUTION: mixture
MIXTURE_NUM_COMPONENTS: 4
MIXTURE_VAR: 0.5
USE_DMD_LOSS: True
DISTILL_LOSS_SCALE: [1.0, 1.0, 1.0, 1.0]
ADVERSARIAL_LOSS_SCALE: [0, 0.1, 0.2, 0.3]
DMD_LOSS_SCALE: [0, 0.3, 0.5, 0.7]
GAN_LOSS_TYPE: lsgan
MODE_PROBS: [
    [0.0, 0.0, 0.5, 0.5],
    [0.1, 0.3, 0.3, 0.3],
    [0.25, 0.25, 0.25, 0.25],
    [0.4, 0.2, 0.2, 0.2],
]
USE_TEACHER_AS_REAL: False
# TEACHER_SCHEDULER: DPMSolverMultistepScheduler
TEACHER_SCHEDULER: PNDMScheduler
SAMPLING_SCHEDULER: LCMScheduler
TEACHER_SAMPLING_SCHEDULER: EulerDiscreteScheduler
USE_EMPTY_PROMPT: True

# Training
LR: 0.00001
LR_DISCRIMINATOR: 0.00001
MAX_EPOCHS: 100
BATCH_SIZE: 1

# Logging
LOG_EVERY_N_BATCHES: 10
NUM_STEPS: [1, 2, 4]
CKPT_EVERY_N_STEPS: 1000
LOG_TEACHER_SAMPLES: True
TEACHER_SAMPLING_GUIDANCE_SCALE: 3.0